### ISSUE TITLE
The Tip Token - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#103]
# [The Tip Token](https://thetiptoken.io/home/) (TTT)

# ‼️ No proof that the Team members are Real ‼️

![the-tip-token-team](https://user-images.githubusercontent.com/32852887/38517764-48e1842c-3c3b-11e8-8ce8-4c3c6c08be06.png)
## Team
- Nicolas Nups (CEO & Founder) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/nicolasnups/)
- Jonathan Teel (CTO & Co-founder) - **Month?** 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/jonathan-teel-119ab5158/) | [Twitter](https://twitter.com/noJ11235)
- Faisal Khan (Community Manager) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/khanfm/)
- Alex Honcharuk (Solutions Architect Consultant) | [Linkedin profile](https://www.linkedin.com/in/honcharuk/) **Does not mention The Tip Token**
- Nick Henry (US Market Expansion Manager) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/nick-henry-b4a3a178/) | [Twitter](https://twitter.com/RidiculousNick1)
- Jamaal Wilson (Online Marketing Strategist & Website Designer) | [Linkedin profile](https://www.linkedin.com/in/vacbusiness/) **Does not mention The Tip Token**
- Phurpa Thapa (System Engineer) | [Linkedin profile](https://www.linkedin.com/in/phurpa-thapa-880048157/) **Does not mention The Tip Token**
- Marc van Dijk (Dutch Market Expansion Manager) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/marc-van-dijk-14668815b/)

![the-tip-token-advisor](https://user-images.githubusercontent.com/32852887/38517798-6c82d782-3c3b-11e8-9d92-e0f92aee1caa.png)
### Advisors
- Micheal O'Brien | [Linkedin profile](https://www.linkedin.com/in/micheal-o-brien-35ba4516/)
- John Tillerson | **No linkedin profile**
- V.N. | **No Name** | **No linkedin profile**
- Mazahar Khan | [Linkedin profile](https://www.linkedin.com/in/mazhar-khan-7a645912/)

# ‼️ No company registered in France ‼️

### ‼️ Founder cannot be found in the French companies registry ‼️
![the-tip-token-nicolas-nups](https://user-images.githubusercontent.com/32852887/38518021-16b40ae6-3c3c-11e8-9fae-ceaafc816b41.png)

## Smart contract
- [Contract on github](https://github.com/thetiptoken/TheTipToken-Contracts)

### Team tokens vest until June 2019. To check in the deployed smart contract.

# Additional info
## ‼️ It is highy probable that Bots are populating the group chat ‼️
![the-tip-token-bot](https://user-images.githubusercontent.com/32852887/38521100-f41e2026-3c44-11e8-8b37-0714720639e6.gif)

### Token distribution
![the-tip-token-distribution](https://user-images.githubusercontent.com/32852887/38519173-3b67e594-3c3f-11e8-8349-bc2ceeb388eb.png)

### Token allocation

# Q&A
![the-tip-token-qa-1](https://user-images.githubusercontent.com/32852887/38517856-94bef9e2-3c3b-11e8-86bb-6e9c25c70024.png)
![the-tip-token-qa-2](https://user-images.githubusercontent.com/32852887/38517866-9de2b0d6-3c3b-11e8-81ce-13485cbbab9a.png)

# Flags
**Real Team:** ❌ Need Proof ‼️  Video, Live Ama etc... Verify Past employment history.
**GitHub:** - No code for the product. Only one repo for the smart contract    
**Smart Contract:** - Not deployed     
**Working Product:** ❌         
**+2 yr Vesting for team:** ❌ Team tokens vest for less than 2 years. To check in the deployed smart contract.       
**Have a company:** ❌ No company registered in France ‼️                
**Transparent:** ❌         

# IcoCheck
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by NicolasNups** [comment]
Good morning,


First of all, we would like to thank you for showing interest in our project. We understand that several points are not finalized yet but we have to keep in mind that we are more than 2 weeks away from the private sale and more than 2 months away from the ITO crowdsale.

However, you have raised valid questions I will answer below : 

**The Team :** 
Regarding the LinkedIn profiles, it was a negligence from our side. We have been focusing a lot on the [website](https://thetiptoken.io) and [whitepaper](http://www.thetiptoken.io/wp-content/uploads/2018/03/TTT-Whitepaper-V3.2.pdf) in the early stages and a couple of members from the team didn't update their LinkedIn. It will be fixed by the time the private sale starts.
Moreover, we can send you over pictures/videos of the team members if this is the kind of proof you are looking for.
As a first proof, **we are pleased to announce our first partnership** : photos of team members and the company owner will be disclosed later today !  

**The advisors :**
Advisors are here to secure the project's well being and prosperity. 
John Tillerson has audited our ITO smart contract and is helpful on various aspects of the ITO. Moreover, VN is working with the team on all the legal aspects of the ITO on daily basis.
They do not wish to share their LinkedIn and I believe this is their right. 
While some projects use advisors name as a brand and an advertisement, we have chosen to use our advisors for the quality help they provide everyday.
We are also being advised by 2 blockchain related projects CEO. They do not wish to be quoted as they cannot be involved in other projects. However, their help matters a lot to us and it helps us directing the project towards the right direction.

**The company :**
The company status and all the necessary documents are signed. In all transparency, the last point that needs to be finalized is the bank account opening.
If you need a proof, I can send you over the signed documents.
As you might be aware of, the french legislation about cryptocurrencies is evolving fast for a couple of weeks; and France has opened to ICO/ITO and crypto related projects. However, banks tend to be slow to keep up.
Nonetheless, you can be assured that the company will be created before any funds are raised.
Another specificity from the french legislation is that as soon as the documents are signed and the bank account is created, the company is officially created; even if the SIRET/SIREN num is not created yet.

**The product :**
We are currently working on a beta product that will be functional before the crowdsale starts. 
As a reminder, I would like to add that we are still more than 2 months away from the crowdsale.

**Vesting :**
A part of the tokens allocated to the team will be used to fund further developments.
If we raise enough funds during the ITO, we might not need them. However, there is still a possibility we would have to.

**Telegram Channel :**
We have started an Airdrop campaign to spread the word about TTT.
Moreover, a youtuber talked about our project and it brought a lot of attention to our [telegram](https://t.me/thetiptoken) in just a couple of days.
Thus, I disagree when polite people saying "hello" are called bots.

**Token distribution :**
If I may, I would like to add an important information about the token distribution. At the end of the Initial Token Offering, all the remaining unsold tokens will be divided like this : 
- 10% will be airdropped to the Initial Token Offering participants
- 20% will be added to the tokens allocated to the ecosystem & airdrops 
- 70% will be burnt

**FAQ :**
A few answers of the FAQ you posted have been updated. 
Kindly come back to me by mail : nicolas.nups@thetiptoken.io or on telegram [@NicoSpun](https://t.me/NicoSpun) if you want more information.

Once again, thank you for showing interest in our project.
I hope my answers could enlighten you on all the points you raised above.


Have a good day,
**Nicolas Nups**
