### ISSUE TITLE
Hero Node - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#120]
# [Hero Node](https://heronode.io/) (HER)

### [![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/HeroNode2) Group chat 2

# ‼️ Rogue Admin stole 500 ETH ‼️
## Whois lookup for HERONODE.IO
```
Domain Name: HERONODE.IO
Registry Domain ID: D503300000056700040-LRMS
Registrar WHOIS Server:
Registrar URL: https://www.gandi.net/whois
Updated Date: 2018-03-30T12:07:01Z
Creation Date: 2017-12-20T08:05:34Z
Registry Expiry Date: 2018-12-20T08:05:34Z
Registrar Registration Expiration Date:
Registrar: Gandi SAS
Registrar IANA ID: 81
Registrar Abuse Contact Email: abuse@support.gandi.net
Registrar Abuse Contact Phone: +33.170377661
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registrant Name: 刘国平 刘
Registrant Organization:
Name Server: F1G1NS2.DNSPOD.NET
Name Server: F1G1NS1.DNSPOD.NET
Name Server: NS-242-B.GANDI.NET
DNSSEC: unsigned
```

# Team
- Guoping Liu (Founder) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/guoping-liu-06aa8815a)
- Daniel (李潇) Li (Co-founder) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/daniel-lixiao/)
- Carl Zhu (CTO) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/carl-zhu-21538092/)
- Yu Yongkai (Jacob) (Co-founder) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/shevckeo) | [Instagram (Private)](https://www.instagram.com/shevckcccc/)
- Ruoxin (Mason) Zhang (Co-founder) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/ruoxin-zhang)
- John Patrick (International Business Development Director) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/john-patrick-mullin/)
- Conghui (Bella) Yang | [Linkedin profile](https://www.linkedin.com/in/conghuiyang/) **does not mention Hero Node Foundation**
- Lilian Lin (CMO) | **No Linkedin profile**
- Gina Li | **No Linkedin profile**
- 李贝贝 (Catherine) (Operation) - Apr 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/贝贝-李-a8a711a0/)
- Eric Clark Su (Overseas Partner and Advisor) - Apr 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/ericsu/)

### Consultant
- Yuhang (Kevin) Guo | [Linkedin profile](https://www.linkedin.com/in/kevin-guo-56b82556/) | [Dianrong](http://en.dianrong.com/about-us/#ns-leadership-team/leader-1)
- Richard Wang | [Linkedin profile]() | [DJF](http://www.dfjdragon.com/cn/team_read.php?id=9)
- Jiarui Liu | [University of San Francisco](https://www.usfca.edu/law/faculty/jiarui-liu)

# Company 
### HERO NODE FOUNDATION LTD.
**Registered Address:**    
9, TEMASEK BOULEVARD       
04-02        
SUNTEC TOWER TWO    
SINGAPORE 038989                    

**UEN:** 201805833C        
**Industry:** COMPUTER PROGRAMMING, CONSULTANCY AND RELATED ACTIVITIES      
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 14 Feb 2018                     
**Status:** LIVE COMPANY                

![heronode-singapore](https://user-images.githubusercontent.com/32852887/39628811-817f8af4-4faa-11e8-89e8-d052c549803d.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

### Linkedin company profile
![heronode-linkedin](https://user-images.githubusercontent.com/32852887/39629194-a3e7eb62-4fab-11e8-9b11-713dabf4551e.png)

# Smart contract
- [View on etherscan](https://etherscan.io/address/0xf00fcd9119f93a1069054e4280970a75614ad7c9)

# Github
- [Hero-node](https://github.com/hero-node)

### Commits
- [Hero node commit activity](https://github.com/hero-node/hero-node/graphs/commit-activity)

# Product
### [Demo](https://heronode.io/dapps)
![heronode-demo](https://user-images.githubusercontent.com/32852887/40327852-a2048282-5d44-11e8-9ebe-e7e9cb8d9fbc.png)

### Mainnet in 2019
![heronode-mainnet-2019-1](https://user-images.githubusercontent.com/32852887/40327803-813ad452-5d44-11e8-9fb7-8714e058614e.png)
![heronode-mainnet-2019-2](https://user-images.githubusercontent.com/32852887/40327806-8332c648-5d44-11e8-98dd-7d91d77270db.png)

### [Hero CLI](https://github.com/hero-node/hero-cli)

# Vesting
- Team tokens vest over 2 years but not coded in the smart contract.

# Additional info
### Token distribution
![hero-node-allocation](https://user-images.githubusercontent.com/32852887/40327601-d3e1727a-5d43-11e8-89eb-a2a4c595cd1c.jpg)

### Token allocation
![heronode-distribution](https://user-images.githubusercontent.com/32852887/40327613-e0a6a804-5d43-11e8-8ad5-4d942c5db2ba.jpg)

# Q&A
### 1. Where is your company registered? Could i have a copy of certificate of incorporation, list of directors and details of registered office address?

>HERO NODE FOUNDATION LTD.       
>UEN:201805833C       
>9 TEMASEK BOULEVARD #04-2 SUNTEC TOWER TWO       
  
>You can check it in website (singapore offical)    

### 2. Can i have details of any intellectual property which the company has created, registered or applied to register?

>You can check it on website (singapore offical)

### 3. Can you share your Cap Table?
>No, I can't share it

### 4. Has there been any change in the shareholders in the past 12 months? If so what and why?
>Yes, Conrerstone invest  

### 5. Has there been any change in the board of the company in the past 12 months? If so who and why?
>Yes, Conrerstone invest  

### 6. Who are the founding team members? What is the citizenship of the founding team? Has the founding team changed in anyway in the past 12 months? If so who and why?

>Me Chinese       
>NG RUENN CHONG SINGAPORE        
>No

### 7. In your team who is a part time employee?
>Eric Clark Su
>Gina Li
>Lilian Lin (full time but in our cornerstone investor company, We are a engineer team)

### 8. Does any of the founding team members have any involvement in helping raise capital for other token projects? Is the person in question regulated to do so?
>Full time，No
>Part Time, May be.

### 9. How much money has the company raised (equity/token) and over what period?
>cornerstone investor 3000 ETH 
>private stage 9000 ETH
>public sale 19000 ETH
>(That is a estimate，We will produce a detailed report，But not from me)

### 10. What is your company's cash burn rate?
>100K USD /month （estimate）

### 11. Is your company GDPR compliant?
>I want to do that，But now I donot know.

### 12. What is the vesting schedule for Team and Advisors token?
>Two years, No Advisors token.

### 13. Is vesting for Team and Advisors coded in the smart contract?
>No, But will public the address .

### 14. is your smart contract deployed for the ICO?
>Yes

### 15. Was your smart contract audited by an independent cybersecurity company? If yes by whom?
>Yes, Standar Token (They donot want to check)

### 16. Could i have a link to your github repo?
>on our website

### 17. Do you have a working product on a testnet? Will mainnet be launched before the crowdsale?
>on our website

### 18. Has the code for your product been published, and has is it been audited by an independent cybersecurity company? If yes by whom?
>Yes, No

### 19. Are you using a reputable 3rd party for KYC verification? How safe is it to upload my Identity Document on your site?
>Thanks for advice. But Sorry for not

### 20. Can us investors participate in the sale? If yes did you secure Reg-D?
>No.

# Heronode Flags
**Real Team:** - More proof needed to verify that all team members work for Hero Node.  
**GitHub:** ✅          
**Smart Contract:** ✅      
**Working Product (Mainnet):** ❌ Heronode is under development.    
**+2 yr Vesting for team:** ❌ Team tokens vest over 2 years but not coded in the smart contract.      
**Have a company:** ✅                
**Transparent:** ❌          

# IcoCheck.io
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by gpliu** [comment]
Haha, May be you can ask me directly. 
TG  @gpliu

**Comment by imivi52** [comment]
Tried to talk with Gpliu - got ignored.
Also found more public pools with bonus up tp 50%.
![pexels-photo-296881 1](https://user-images.githubusercontent.com/38981684/39661747-5e4f2ca0-505f-11e8-8690-af5a54b86f37.jpeg)
![74](https://user-images.githubusercontent.com/38981684/39661749-650edc2a-505f-11e8-9916-c64d5e92bfbd.png)
![75](https://user-images.githubusercontent.com/38981684/39661750-664acae0-505f-11e8-832b-ac978be35594.png)

**Comment by imivi52** [comment]
Bonuses issue solved - difference was with discount/bonus rates. Some pools were "baiting" on bonus size, also pools were counting discount as a bonus rate. So 30% discount is 42.8% bonus

**Comment by imivi52** [comment]
Hello! So here is p2 of investigation on Hero node. In previous post I mentioned problems with bonus size, transactions, etc.
So what changed? Nothing. About bonuses – issue was solved, but I still can’t understand how public pool can be a strategic partner and give project any publicity. Anyway GP answer about transactions on HERO-NODE ICO was literally this: “Hero node is my project and I can send ETH anywhere I want to” (Not exact answer, but close to this one, also the answer was given not to me directly, but to friend of mine, just FYI. Anyway, it doesn’t matter, coz we will talk about other things). Ok, let’s forget about previous red flags and move forward. The most interesting part started then I was trying to invest. Before sending funds, I decided to check SAFT one more time and noticed, that agreement isn’t signed from foundation side.
![81](https://user-images.githubusercontent.com/38981684/39772266-dec7a4e4-5298-11e8-8ee0-8e473adafb6b.jpg)
So, I tried to send them an e-mail to market@heronode.io to get signed SAFT, but didn’t got replied. That’s why I decided to talk with admin of Heronode and GP directly. First of all, I decided to talk with their admin AKA Nuclear Fission (@Nitroxen0n). So, first of all admin offered me to send a new contract (She didn’t realize that I already have one and offered to make a new one).
![82](https://user-images.githubusercontent.com/38981684/39772282-f0ebf8be-5298-11e8-83a2-f709d4671f48.jpg)
Then she called me via Telegram and we were discussing SAFT for a few min, during a call she said that agreement should be signed from their side (But I think that it was just misunderstanding, coz she was not from English-speaking country).
![83](https://user-images.githubusercontent.com/38981684/39772300-fe5713b2-5298-11e8-966d-53e0be9d8fb7.png)
Anyway, then she told me that contract has been already signed. So I send her screen of my SAFT to check, and she told me that it’s a scam SAFT. I was like “Whaaat?”, coz I got my SAFT directly from GPliu.
![545](https://user-images.githubusercontent.com/38981684/39772316-109182ec-5299-11e8-8220-554f0a22b4e8.png)
After I told her that I got this SAFT from market@heronode.io she told me that the SAFT is still a scam (Coz the real one has GP’s signature on it) and sent me an example. Right after that I forwarded GP’s msg to her, to prove that he gave me that information, and she said, that “PRESALE IS CLOSED” (But as we remember at the start she offered me a new contract, so did the situation changed for a few minutes?!). 
![screenshot_1](https://user-images.githubusercontent.com/38981684/39772339-1b835fcc-5299-11e8-8c1d-33452bb21144.png)
After my question “How it’s possible, that official e-mail sending fake SAFTs?” she started to claim, that her colleague from heronode foundation was trying to scam me! (Bust we will figure out later, my SAFT was the real one LOL)
![screenshot_3](https://user-images.githubusercontent.com/38981684/39772363-28f45d6e-5299-11e8-89ff-f074c8813ebf.png)
And here come THE SURPRISE, AND # ADMIN STOLE 500 ETH IN TOTAL!! So please be aware, that someone stole 500 ETH from the project.
![screenshot_4](https://user-images.githubusercontent.com/38981684/39772398-43e3fa12-5299-11e8-98fa-860ecbf8e24f.png)
Later we figured out, that my SAFT is the real one (Just compared ETH wallet from her and my SAFT). But my SAFT wasn’t signed from their side (Ok, it might be just someone small mistake).
![screenshot_5](https://user-images.githubusercontent.com/38981684/39772415-503e4d8a-5299-11e8-866e-2d8d45d70528.png)
Cool, but after she offered my still to send ETH (Instead of other guy, SO WHAT THE HELL IS GOING ON IF ADMIN WANT TO MAKE A REFUND TO OTHER INVESTOR AND GIVE HIS ALLOCATION TO YOU LOL?!) (The story was that were was a guys, who sent only 180/300 ETH, so they offered me to fill 120 ETH, but right after offered to refund him 180 ETH and give me whole allocation (120+180 ETH). Also there a little bit more info about admin scammer. 
![screenshot_6](https://user-images.githubusercontent.com/38981684/39772439-5cd39960-5299-11e8-857d-c3563a84f66d.png)
Just to confirm that she is an admin adding her pinned post in main heronode group
![screenshot_7](https://user-images.githubusercontent.com/38981684/39772449-65c3f83a-5299-11e8-9191-41033d55a79f.png)
Ok, so what is the conclusion? I would stay away from the project, a lot off “bad” things are around it. Btw, it would be cool, if GPLIU (CEO of heronode, who previously made a post here, pretending that he is ready to answer on all questions directly) would read his telegram, and didn’t ignore ppl (including me) who just wants to figure out the situation, coz I still didn’t got replied for a few days (question was about transactions on the HERO node wallet).
IT’S my personal opinion and the project might not be a scam (Probably it’s not), but I would stay away from it.

**Comment by Snake4life** [comment]
lack of transparency, very high risk to invest, be warned!

![11](https://user-images.githubusercontent.com/13849408/39922018-6b3f7592-551d-11e8-962f-16d4948fae8c.PNG)
![22](https://user-images.githubusercontent.com/13849408/39922020-6b58fa94-551d-11e8-97ce-3c5c14147f6f.PNG)

**Comment by imivi52** [comment]
They might keep only admin (That happened right after i send this page to GPliu), so now Nuclear Fission might be kicked out (They changed pinned msg)

**Comment by Snake4life** [comment]
I have seen Nuclear Fission as an Admin some days ago, they might have kicked her because she "leaked" the info about the scam, they try to hide it

**Comment by NemyaNation** [comment]
Shame because the decentralized fog computing is new. Was excited about this project :(

**Comment by gpliu** [comment]
I will make everything transparent，I'm GP，also @gpliu directly

**Comment by gpliu** [comment]
One of our volunteer administrators did a really bad job on the project，I fired her，and announced many times in the group, But still some was scammed. I promised to help them.

**Comment by smartins** [comment]
Volunteer administrator? Really? You trust someone who you are not paying or compensating to have an admin status and handle sensitive matters? How can projects be raising millions of dollars and be so cheap as to not properly vet and compensate those who help out with the ico?

**Comment by gpliu** [comment]
This was my fault. At the beginning of the project, I really needed a ‘time difference’ volunteer to help me delete advertisements and other news. When I discovered that she had contacted investors alone, we removed her and broadcast many times. I will still be responsible for this.

**Comment by jeffreyrufino** [comment]
Did they recover the stolen ETH?

**Comment by compfp** [comment]
John Patrick does mention Hero Node. From his Linkedin profile:

![image](https://user-images.githubusercontent.com/25405420/40266842-88cb7774-5b52-11e8-920f-07bcacea782c.png)
