### ISSUE TITLE
Cypherium - Due diligence

### ISSUE THREAD

**Issue by dshuang** [ico-check/ico-check#27]
# [Cypherium](https://www.cypherium.io) (CPH)

## Team
- Sky Guo (Founder) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/sky-guo-b9432574/) **To verify**
- Nate Ren (Co-Founder) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/nate-ren-32414a14/) **To verify**
- 张昊翀 Solomon Zhang (Co-Founder) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/%E6%98%8A%E7%BF%80-%E5%BC%A0-79b46891/) **To verify**
- Sinful (Developer) | **No linkedin profile**
- Sicong Zhuang (Blockchain Researcher) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/sicong-zhuang-27471459/)
- Fanghua (Joe) Qiao (Title) | [Linkedin profile](https://www.linkedin.com/in/fanghua-joe-qiao-89958542/) **does not mention Cypherium**
- Anker Chen (Developer) - Sep 2015 - Present | **No linkedin profile**
- Eric P. S. (European Affair Director) | **No last name**
- Mike Eekhof (European Affair Assistant Netherlands) | **No linkedin profile**
- Hans Eyman (Business Analyst) | **No linkedin profile**
- Shi Pu | **No linkedin profile**

### Advisors
- Emin Gün Sirer | [Linkedin profile](https://www.linkedin.com/in/emin-gun-sirer-0a921a4/)
- Jeremy Gardner | [Linkedin profile](https://www.linkedin.com/in/jg1578/)

## Company 
![cypherium-hong-kong](https://user-images.githubusercontent.com/32852887/34590576-f10abd0e-f1b7-11e7-8419-89ee0119a357.png)

### Kexing Info & Tech Company Limited
**Registered Address:**
FLAT B, 4/F, Kingswell Commercial Tower          
171-173 Lockhart road       
Wanchai       
Hong Kong        

**CR No.:** 2616387       
**Company Type:** Private company limited by shares      
**Date of Incorporation:** 30 Nov 2017      
**Active status:** Live      

**Class of shares:** Ordinary        
**Total number of shares:** 10,000        
**Currency:** HKD        

### GUO "SKY", JIAN HUA (DIRECTOR)              
**Share capital:** 9,400  

### GUO, YANG RUI (??)                
**Share capital:** 599  

### Full Moral Management Limited    
FLAT B, 4/F, Kingswell Commercial Tower            
171-173 Lockhart road       
Wanchai       
Hong Kong    
**Share capital:** 1

### [ICRIS - Companies Registry](https://www.icris.cr.gov.hk/csci/)
![cypherium-name-1](https://user-images.githubusercontent.com/32852887/34591639-50183f9a-f1bf-11e7-8444-d5371347d565.png)

- Founder **GUO "SKY", JIAN HUA** is the majority shareholder of the company. Co-founder **Nate Ren** and **Solomen Zhang** are not shareholders of the company.

## Smart contract
![cypherium-smart-contract-1](https://user-images.githubusercontent.com/32852887/34591722-d5535320-f1bf-11e7-8f76-a51fdab801e9.png)
![cypherium-smart-contract-2](https://user-images.githubusercontent.com/32852887/34591723-d6ca055a-f1bf-11e7-8f10-a3e1b23976b8.png)
![cypherium-smart-contract-3](https://user-images.githubusercontent.com/32852887/34591738-efa9d636-f1bf-11e7-8616-ee9fde453407.png)
- Tokens will be distributed in the Cypherium wallet after the main net Q2 2018

## Github
![cypherium-github](https://user-images.githubusercontent.com/32852887/34592117-23813844-f1c2-11e7-8121-213aba6c8769.png)
- ~~Not available. Team says code is in a private repo.~~ 

### Update:
[Cypherium Blockchain](https://github.com/cypherium)

## Product
![cypherium-product](https://user-images.githubusercontent.com/32852887/34591762-15870cde-f1c0-11e7-943a-a499b8b655b7.png)
- No working product available to test yet. Founder says prototype released in January 2018
- [Cypherium Virtual Machine Specification (Draft)](https://github.com/cypherium/cvm)

## Vesting
![cypherium-vesting](https://user-images.githubusercontent.com/32852887/34591770-1d1aa208-f1c0-11e7-8820-0093dbe4b568.png)
- 2 years vesting schedule for team tokens ( Need proof )
### Token distribution
![cypherium-distribution](https://user-images.githubusercontent.com/32852887/34592176-915e6684-f1c2-11e7-9531-38757f87188c.jpg)

**Comment by city19akro** [comment]
For some more info on Cypherium, i made a twitter thread a while ago: https://twitter.com/city19akro/status/975342278146428928
I threaded it like shit so more info here:
https://twitter.com/city19akro/status/975367139615035392
https://twitter.com/city19akro/status/975366638672535555
https://twitter.com/Peeeeertje/status/975360100360769537

To recap fully (also stuff that isn't on twitter)

- The token metrics were not really clear and (some) private sale investors invested with the impression that unsold tokens (Due to $ hard cap being reached) would be distributed to investors. It was quite important as it would basically double the stake.
- Cypherium team said those tokens might be taken for "partnerships" (although they had more than enough tokens for themselves)
- In the end the community managers and marketing manager quit over the conflict at they thought the investors were being unfairly treated
- Cypherium team announced the unsold tokens would be burnt (and not redistributed) which displeased a lot of investors. However they offer to give those who asked a refund
- A week or so later it was found that the contribution ETH was moved, first consolidated to here https://etherscan.io/address/0xbc3175b1054214acea52127f3de1b7b243844670 and then sent to here https://etherscan.io/address/0x94f20ccff70d82d1579d8b11f2985f8de9b287cf. When you googled the address it appeared on a russian bitcointalk thread https://bitcointalk.to/index.php?topic=2996289.140
- There was a comment by cypherium btctalk account in that thread asking information about those addresses saying they're investigating them (google translated since it was in russian - one of their admins is/was russian) - this post has since (since i made the twitter thread) been removed but it was quoted by another commenter: https://bitcointalk.org/index.php?topic=2996289.msg31758765#msg31758765
- Meanwhile several investors found this out and asked questions in the telegram group (everything was deleted). They also asked via pm to Nate & Sky Guo (the Execs of Cypherium). Both eventually confirmed that there was a security breach and the funds were somehow compromised (however they deleted all PMs afterwards but screenshots from multiple investors remain & their advisors have also acknowledged the hack - in private at least).
- Some investors managed to get a refund before the hack happened (I know I did a day before it happened) but a lot did not and cypherium team kept delaying the requests
- Cypherium team is denying the hack and calling it 'FUD' in public. They've also threatened several people (including me) of criminal charges ('obstruction of justice') and lawsuits over the fact we disclosed or talked about the hack. They said in private to some people the FBI was involved and to some their lawyers were involved - that their computers were under forensics investigations etc but are still refusing to disclose it publicly.
- During all that time, potential investors have shown interest for the token and were not told anything about this situation. Some people that were originally put on the waitlist were contacted AFTER THE HACK WAS KNOWN BY CYPHERIUM and asked if they wanted to invest but they never disclosed to them they got hacked.
- Investors that wanted their refunds complained via private email as well and said they'd go to the SEC if they didn't get their refunds. They were also threatened of obstruction of justice and told that Cypherium is outside of the jurisdiction of the SEC (but somehow the FBI is helping them investigate the hack??)
- AFAIK they're still refusing to disclose any of this to potential investors. I (and multiple other past or present investors) have been banned when raising those concerns. The telegram admins actively say all of this is "FUD" and "unproven" when it's in fact quite the contrary....

Anyways I got a few screenshots of this (some coming from other investors, some are mine - in the twitter thread). Some are also somewhat confidential and not willing to divulge yet especially because of mentioned threats or because I did not get authorisation from the source yet.
