### ISSUE TITLE
NKN - Due Diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#75]
# [NKN](https://nkn.org/) (NKN)

## Team
- Yanbo Li (Founder & Core Developer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yanbo-li-b478585/) | [Github](https://github.com/dreamfly281)
- Zheng Li (Bruce) (Co-Founder & Strategy & Innovation) - Mar 2018 - Present | [Linkedin](https://www.linkedin.com/in/zbruceli/) | [Github](https://github.com/zbruceli)
- Justin Wang (Co-Founder & Core Researcher) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/justin-wang-99b36016/) | [Github](https://github.com/barbapapait)
- Yilun Zhang (Co-Founder & Core Researcher & Developer) - Feb 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yilun-zhang-/) | [Github](https://github.com/yilunzhang)
- Allen Dixon (Business Development & Compliance) - **Month?** 2017 - Present  | [Linkedin](https://www.linkedin.com/in/dixonal/)

## More information needed to verify other team members
- Aaron Jow (Core Developer) | [Linkedin](https://www.linkedin.com/in/aaron-jow-557b6075/) **Possible profile**
- Oscar.C (Core Developer)
- Mouxin Mo (Core Developer)
- King.K (Core Developer)
- Zhiguo Hong (Community Core Developer) | [Linkedin](https://www.linkedin.com/in/zhiguo-hong-9407bb35/) **Possible profile** | [Github](https://github.com/honkiko) **Possible profile**
- Chenxing Li (Community Core Researcher & Developer)
- Annie Liu (Community Researcher & Developer)

### Advisors
- Whitfield Diffie | [Wikipedia](https://en.wikipedia.org/wiki/Whitfield_Diffie)

# Company 
## NKN FOUNDATION LTD.
**Registered Address:**    
9 TEMASEK BOULEVARD          
04-02       
SUNTEC TOWER TWO       
SINGAPORE 038989                        

**UEN:** 201808264M       
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 9 Mar 2018    
**UEN Status:** REGISTERED                    
**Status:** LIVE COMPANY        

![nkn-foundation](https://user-images.githubusercontent.com/32852887/37751888-4c275d6e-2d95-11e8-9c80-f56a92df5a6f.png)

### [NKNToken](https://github.com/doraemon0/ERC20-token/blob/master/NEP-5/NKNToken.cs)
- Tokens are NEO NEP-5

## Github
- [NKNetwork](https://github.com/NKNetwork)

## Product
- Testnet Q1 2019
- Mainnet Q3 2019

![nkn-testnet](https://user-images.githubusercontent.com/32852887/38477436-c749ecf2-3bb2-11e8-9655-1fcd468c027f.png)

### Product roadmap
![nkn-roadmap](https://user-images.githubusercontent.com/32852887/38501564-994c2f8a-3c0d-11e8-927c-64aa2ad06f65.png)

## Additional info   
- NEP-5 NKN token can be 1:1 exchanged for a native NKN token once mainnet is live (Q3 2019)

### Token distribution
- **17% NKN Foundation** | Build the NKN Community and Network
- **18% Developers** | For developers and advisors 
- **30% Miners** | Generated through "mining" over an estimated 25-year period
- **35% Purchasers** | 
 
### Token allocation
N/A

# Flags
**Real Team:** ✅       
**GitHub:** ✅          
**Smart Contract:** - Neo. Not yet deployed.      
**Working Product:** ❌  Testnet Q1 2019, Mainnet Q3 2019  
**+2 yr Vesting for team:** Check codified vesting in the neo smart contract        
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by UDCER** [comment]
Have you read their disclaimer though? The NKN FOUNDATION LTD is an EXEMPT "PRIVATE" (AKA Privately Owned) COMPANY LIMITED BY SHARES in Singapore. And in their disclaimer points a-e if you / we participate in their ICO, if they have one already, or buy the nkn token on crypto exchanges, & something goes wrong we nkn token/coin holders have no rights against the owners of the NKN FOUNDATION, or its board of directors, no matter what happens. Even If, as an extreme case, they decide to keep them all for themselves because it's "miraculously going so well" - there is absolutely nothing we can do as there are no laws protecting us. 

Therefore, I think if this were anything more than a highly experimental project based on unproven, therefore unscientific, theories of the most abstract kind, that have been challenged long ago by equally compelling Theories/Arguments (Narratives) in academia, it could take decades to incarnate into real world "physical" usage - if ever! If they were further down the track with it than this I think they would have offered it more genuinely as a Security Token, which is protected by the same laws as shares in a publicly listed Company & NOT a Privately owned one whereby the shareholders (nkn token owners) don't have any influence over the Company in any way. The owners have "Carte Blance" to do whatever they like with it & any funds they raise / raised with no accountability or governance input by us poor token holders. Talk about a "Centralised System/Organisation"! 

This is the ideal way of setting one up! It's way more centralised than the FAANG's etc of the world where at least shareholders get to vote on agendas/plans of the Co's at their AGM's & every single one of their shares has legal rights of "ownership" (a fundamental principle of democracy) attached to them to protect the shareholders from Directors/Large owner/Founders ripping us off! 

Whatever happened to the concept of the DAO & Decentralisation in Crypto altogether? This project should never be considered a true cryptocurrency based project as it surely isn't. Indeed NGN is governed by precisely the opposite values & structure to crypto-economic values whereby the owners of the service (holding the crypto Tokens/Coins) also govern & profit from the service every time they or anyone else uses it!
